{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "707b437a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter software salary per month:1670000\n",
      "enter income tax per month:890000\n",
      "you have no tax for month:\n"
     ]
    }
   ],
   "source": [
    "N=int(input(\"enter software salary per month:\"))\n",
    "L=int(input(\"enter income tax per month:\"))\n",
    "if N>L and N<=L:                                                 # CONDITIONAL STATEMENTS PROGRAM USING S/W SALARY AND \n",
    "    print(\"you have tax for month:\")                                            #IN/TX PER MONTH\n",
    "elif N<L or N!=L:\n",
    "    print(\"you have no tax for month:\")\n",
    "else:\n",
    "    print(\"you are a student:\")\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "01083e8c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
